// File generated by FlutterFire CLI / WatchHive configuration.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] used by `Firebase.initializeApp`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtWc9rgM2yC9Fq0vypl0XB-PX_z7mklpU',
    appId: '1:672257580593:android:8f3075079b8565f625ff10',
    messagingSenderId: '672257580593',
    projectId: 'studio-9462568570-5a4a5',
    storageBucket: 'studio-9462568570-5a4a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtWc9rgM2yC9Fq0vypl0XB-PX_z7mklpU',
    appId: '1:672257580593:ios:8f3075079b8565f625ff10',
    messagingSenderId: '672257580593',
    projectId: 'studio-9462568570-5a4a5',
    storageBucket: 'studio-9462568570-5a4a5.firebasestorage.app',
  );
}
